# Generated by Django 4.2.6 on 2023-10-13 13:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_tag_alter_clientmodel_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='messagemodel',
            name='status',
            field=models.IntegerField(choices=[(1, 'Sent'), (2, 'Waiting'), (3, 'Not sent')], default=3),
        ),
    ]
