# Generated by Django 4.2.6 on 2023-10-15 17:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_operatorcodemodel_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clientmodel',
            name='operator_code',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='api.operatorcodemodel'),
        ),
        migrations.AlterField(
            model_name='clientmodel',
            name='timezone',
            field=models.CharField(max_length=50),
        ),
    ]
