# Generated by Django 4.2.6 on 2023-10-15 18:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_alter_clientmodel_operator_code_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='TimeZoneModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=63)),
                ('timezone', models.CharField(max_length=63, unique=True)),
            ],
            options={
                'verbose_name_plural': 'Временная зона',
            },
        ),
        migrations.AlterModelOptions(
            name='operatorcodemodel',
            options={'verbose_name_plural': 'Код оператора'},
        ),
        migrations.AlterField(
            model_name='clientmodel',
            name='timezone',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='api.timezonemodel'),
        ),
    ]
