# Generated by Django 4.2.6 on 2023-10-15 18:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_timezonemodel_alter_operatorcodemodel_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mailinglistmodel',
            name='operator_code',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='api.operatorcodemodel'),
        ),
    ]
