# Generated by Django 4.2.6 on 2023-10-17 06:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('django_mailing', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CustomUser',
        ),
    ]
